### GET /
GET http://localhost:5173

### Register a user POST /api/auth/register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password" : "123456"
}

### Login a user POST /api/auth/login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password" : "123456"
}
